### PR TITLE
4-3 修复

### PR DESCRIPTION
**Pull request by diskrubbish**
稀理辉石->赛德瑞瑟晶体，最后还是统一翻译吧，改回这种罗马音日式音译总觉得好遗憾，就像史东薇尔那样。。。
”chs“和"Chs"看似相同，但是大小写问题会影响翻译导出，这次我替换了，下次注意@HaKiKKK
还有，老陈，颜色标记的;不能打成；，已经有很多的颜色标记失效了。。。机翻整理格式的时候记得注意一下@ChenJunsen

### CODE REVIEW

**Comment by diskrubbish** [comment]
我说的有点夸张。。。哎，自己最近也是犯错连篇，状态不好啊。

**Comment by HaKiKKK** [comment]
我的锅，第一次翻译难免出错

**Comment by ChenJunsen** [comment]
好的好的。我后面改进一下机翻脚本。

**Comment by ChenJunsen** [comment]
最近成都疫情愈发严重，加上公司事多，都无暇翻译了。

**Comment by ChenJunsen** [comment]
好的好的，机翻的脚本实际是专门过滤了颜色字符。我后面再研究一下。2022年4月3日 22:04，diskrubbish ***@***.***>写道：稀理辉石->赛德瑞瑟晶体，最后还是统一翻译吧，改回这种罗马音日式音译总觉得好遗憾，就像史东薇尔那样。。。

***@***.***

***@***.***







You can view, comment on, or merge this pull request online at:

  https://github.com/ProjectSky/FrackinUniverse-sChinese-Project/pull/437



Commit Summary

0d3274b  4-3 修复187b23d  4-3 前缀修复



File Changes  (72 files)



    M

    dictionary/core_diskrubbish.yml

    (2)

  

    M

    documents/NOTE.md

    (8)

  

    M

    memory.json

    (80)

  

    M

    translations/texts/codex/skath/skathfallenfortress.codex.json

    (8)

  

    M

    translations/texts/codex/skath/skathfirstcontactwar.codex.json

    (16)

  

    M

    translations/texts/codex/skath/skathfortress.codex.json

    (12)

  

    M

    translations/texts/codex/skath/skathhistory1.codex.json

    (8)

  

    M

    translations/texts/codex/skath/skathhistory2.codex.json

    (8)

  

    M

    translations/texts/codex/skath/skathhistory3.codex.json

    (6)

  

    M

    translations/texts/codex/skath/skathhistory4.codex.json

    (8)

  

    M

    translations/texts/codex/skath/skathhistory5.codex.json

    (10)

  

    M

    translations/texts/codex/skath/skathhistory6.codex.json

    (8)

  

    M

    translations/texts/interface/cockpit/cockpit.config.json

    (2)

  

    M

    translations/texts/interface/scripted/fu_matmodplacer/fu_matmodplacer.config.json

    (2)

  

    M

    translations/texts/items/active/shields/xithriciteshield.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/boomerang/xithriciteboomerang.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/bow/xithricitebow/xithricitebow.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/chakram/xithricitechakram.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/fist/xithricitefist.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/melee/axe/xithriciteaxe.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/melee/broadsword/xithricitebroadsword.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/melee/dagger/xithricitedagger.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/melee/hammer/xithricitehammer.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/melee/katana/xithricitekatana.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/melee/longsword/xithricitelongsword.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/melee/mace/xithricitemace.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/melee/quarterstaff/xithricitequarterstaff.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/melee/rapier/xithriciterapier.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/melee/shortspear/xithriciteshortspear.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/melee/shortsword/xithriciteshortsword.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/melee/spear/xithricitespear.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/ranged/unique/xithriciteassaultrifle.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/ranged/unique/xithricitepistol.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/ranged/unique/xithriciterocketlauncher.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/ranged/unique/xithriciteshotgun.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/ranged/unique/xithricitesmg.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/ranged/unique/xithricitesniper.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/staff/orestaffs/xithricitestaff.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/wand/orewands/xithricitewand.activeitem.json

    (2)

  

    M

    translations/texts/items/active/weapons/whip/xithwhip.activeitem.json

    (2)

  

    M

    translations/texts/items/armors/tier6/fuxithricitearmor/fuxithricite.chest.json

    (2)

  

    M

    translations/texts/items/armors/tier6/fuxithricitearmor/fuxithricite.head.json

    (2)

  

    M

    translations/texts/items/armors/tier6/fuxithricitearmor/fuxithricite.legs.json

    (2)

  

    M

    translations/texts/items/generic/crafting/xithriciteore.item.json

    (2)

  

    M

    translations/texts/monsters/skills/ranged/shared_attack.monsterskill.json

    (35)

  

    M

    translations/texts/objects/generic/flagfufenerox/flagfufenerox.object.json

    (2)

  

    M

    translations/texts/objects/generic/storage/genecabinet.object.json

    (2)

  

    M

    translations/texts/objects/petspawners/cleaningbotpetspawner/cleaningbotpetspawner.object.json

    (2)

  

    M

    translations/texts/objects/petspawners/crasberrypetspawner/crasberrypetspawner.object.json

    (2)

  

    M

    translations/texts/objects/petspawners/dogpetspawner/dogpetspawner.object.json

    (2)

  

    M

    translations/texts/objects/petspawners/fennixpetspawner/fennixpetspawner.object.json

    (2)

  

    M

    translations/texts/objects/petspawners/fluffalocalfpetspawner/fluffalocalfpetspawner.object.json

    (2)

  

    M

    translations/texts/objects/petspawners/ixolingpetspawner/ixolingpetspawner.object.json

    (2)

  

    M

    translations/texts/objects/petspawners/lilodonpetspawner/lilodonpetspawner.object.json

    (2)

  

    M

    translations/texts/objects/petspawners/mooshicalfpetspawner/mooshicalfpetspawner.object.json

    (2)

  

    M

    translations/texts/objects/petspawners/orbispetspawner/orbispetspawner.object.json

    (2)

  

    M

    translations/texts/objects/petspawners/petricubpetspawner/petricubpetspawner.object.json

    (2)

  

    M

    translations/texts/objects/petspawners/piglettpetspawner/piglettpetspawner.object.json

    (2)

  

    M

    translations/texts/objects/petspawners/poptoppetspawner/poptoppetspawner.object.json

    (2)

  

    M

    translations/texts/objects/petspawners/quagmuttpetspawner/quagmuttpetspawner.object.json

    (2)

  

    M

    translations/texts/objects/petspawners/snakepetspawner/snakepetspawner.object.json

    (2)

  

    M

    translations/texts/objects/petspawners/snuffishpetspawner/snuffishpetspawner.object.json

    (2)

  

    M

    translations/texts/objects/petspawners/snuggetpetspawner/snuggetpetspawner.object.json

    (2)

  

    M

    translations/texts/objects/petspawners/sporguspetspawner/sporguspetspawner.object.json

    (2)

  

    M

    translations/texts/objects/petspawners/weaselpetspawner/weaselpetspawner.object.json

    (2)

  

    M

    translations/texts/objects/scb-flametrap/scb-flametrap.object.json

    (2)

  

    M

    translations/texts/objects/scb-poisontrap/scb-poisontrap.object.json

    (2)

  

    M

    translations/texts/objects/scienceoutpost/burgerfool/burgerfool.object.json

    (2)

  

    M

    translations/texts/wide_spread_fields.json

    (2)

  

    M

    translations/texts/zb/researchTree/fu_craftsmanship.config.json

    (4)

  

    M

    translations/texts/zb/researchTree/fu_geology.config.json

    (4)

  

    M

    translations/texts/zb/researchTree/fu_warcraft.config.json

    (2)

  



Patch Links:

https://github.com/ProjectSky/FrackinUniverse-sChinese-Project/pull/437.patchhttps://github.com/ProjectSky/FrackinUniverse-sChinese-Project/pull/437.diff

**Pull request merged**
